
all: q1 q2 q3 q3_nowait

clean:
	rm -f q1 q2 test.txt q3 q3_nowait

q1: q1.c
	gcc -o q1 q1.c -Wall

q2: q2.c
	gcc -o q2 q2.c -Wall

q3: q3.c
	gcc -o q3 q3.c -Wall

q3_nowait: q3_nowait.c
	gcc -o q3_nowait q3_nowait.c -Wall