
all: q1 q2 q3 q3_nowait q4 q5 q6

clean:
	rm -f q1 q2 test.txt q3 q3_nowait q4 q5 q6

q1: q1.c
	gcc -o q1 q1.c -Wall

q2: q2.c
	gcc -o q2 q2.c -Wall

q3: q3.c
	gcc -o q3 q3.c -Wall

q3_nowait: q3_nowait.c
	gcc -o q3_nowait q3_nowait.c -Wall

q4: q4.c
	gcc -o q4 q4.c -Wall

q5: q5.c
	gcc -o q5 q5.c -Wall

q6: q6.c
	gcc -o q6 q6.c -Wall
